// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2ro59qZ20XYMCydndpMXgeRJ6HmaEoQ',
    appId: '1:778334362913:web:93f0fc2dcf924789043260',
    messagingSenderId: '778334362913',
    projectId: 'fleet-track-486de',
    authDomain: 'fleet-track-486de.firebaseapp.com',
    storageBucket: 'fleet-track-486de.firebasestorage.app',
    measurementId: 'G-4GXB36L0TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANW4J1lcEgppzQbnmN51YCe5ISgmHlz54',
    appId: '1:778334362913:android:7b474652a6954ae9043260',
    messagingSenderId: '778334362913',
    projectId: 'fleet-track-486de',
    storageBucket: 'fleet-track-486de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOsaCcvwUnMrXMenOY5FEn6b7pqggRsl8',
    appId: '1:778334362913:ios:838c0fb41bf1242c043260',
    messagingSenderId: '778334362913',
    projectId: 'fleet-track-486de',
    storageBucket: 'fleet-track-486de.firebasestorage.app',
    iosBundleId: 'com.example.technicianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOsaCcvwUnMrXMenOY5FEn6b7pqggRsl8',
    appId: '1:778334362913:ios:838c0fb41bf1242c043260',
    messagingSenderId: '778334362913',
    projectId: 'fleet-track-486de',
    storageBucket: 'fleet-track-486de.firebasestorage.app',
    iosBundleId: 'com.example.technicianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb2ro59qZ20XYMCydndpMXgeRJ6HmaEoQ',
    appId: '1:778334362913:web:57a8676ad4ee405a043260',
    messagingSenderId: '778334362913',
    projectId: 'fleet-track-486de',
    authDomain: 'fleet-track-486de.firebaseapp.com',
    storageBucket: 'fleet-track-486de.firebasestorage.app',
    measurementId: 'G-LMQ3QKCC86',
  );
}